# Generated by Django 5.1.7 on 2025-03-15 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='medical_uni',
            new_name='state_medical_council',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
        migrations.AddField(
            model_name='doctor',
            name='aadhar_no',
            field=models.CharField(default='000000', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prac_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.address'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(default='000000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='year_of_registration',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medical_license_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='aadhar_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aadhar_doc', to='main_app.document'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qualification_docs', to='main_app.document'),
        ),
    ]
