# Generated by Django 5.1.7 on 2025-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_dob_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
