# Generated by Django 4.2.7 on 2025-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medications',
            field=models.JSONField(default=list),
        ),
    ]
